# Generated by Django 3.2.7 on 2021-09-27 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(default='14 dígitos', max_length=14)),
                ('razaoSocial', models.CharField(default=' ', max_length=10)),
                ('email', models.CharField(default=' ', max_length=50)),
                ('cidade', models.CharField(default=' ', max_length=20)),
                ('estado', models.CharField(default='Ex: SP', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(default=' ', max_length=15)),
                ('produto', models.CharField(default=' ', max_length=100)),
                ('marca', models.CharField(default=' ', max_length=20)),
                ('quantidade', models.IntegerField()),
                ('empresa', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='app.empresas')),
            ],
        ),
    ]
