# Generated by Django 3.2.7 on 2021-09-25 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210922_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='empresa',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='app.empresas'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='cnpj',
            field=models.CharField(default=' ', max_length=14),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='codigo',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='marca',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='produto',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
