# Generated by Django 3.2.7 on 2021-09-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210924_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='id',
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.CharField(default='14 dígitos', max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='cnpj',
            field=models.CharField(default=' ', max_length=14, primary_key=True, serialize=False),
        ),
    ]
